# WHAT IS PYTORCH?
It's a Python-based scientific computing package targeted at two sets of audiences:
- A replacemenet for NumPy to use the power of GPUs
- a deep learning research platform that provides maximum flexibility and speed

## Getting Started
### Tensor
Tensors are similar to NumPy's ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 9.3388e-01,  3.0931e-41,  3.1228e-17],
        [ 4.5629e-41,  2.9690e-17,  4.5629e-41],
        [-3.1693e-07,  4.5628e-41, -3.1693e-07],
        [ 4.5628e-41, -3.1693e-07,  4.5628e-41],
        [ 1.3434e-05,  3.3858e-06,  1.6914e+22]])


Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7815, 0.6552, 0.8038],
        [0.0779, 0.9889, 0.6256],
        [0.9765, 0.7067, 0.8995],
        [0.9746, 0.3690, 0.4158],
        [0.1849, 0.6882, 0.1473]])


Construct a matrix filled zeros and of dtype long:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an exiting tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [6]:
x = x.new_ones(5, 3, dtype=torch.double) # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float) # override dtype!
print(x) # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.8681,  2.3287,  0.0230],
        [ 0.9290, -1.0131,  1.1736],
        [ 0.1683, -0.2340,  0.2020],
        [ 0.5596,  1.9892, -2.1515],
        [ 0.1771,  0.3354, -2.0140]])


Get its size:

In [7]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports all tuple operations.

### Operations
There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1

In [8]:
y = torch.rand(5, 3)
print(x * y)

tensor([[ 1.2869,  0.3313,  0.0018],
        [ 0.8448, -0.4798,  0.1028],
        [ 0.1581, -0.0516,  0.0030],
        [ 0.1842,  0.1364, -1.2277],
        [ 0.1601,  0.1836, -0.7949]])


Addition: syntax 2

In [9]:
print(torch.add(x, y))

tensor([[ 3.3168,  2.4710,  0.1030],
        [ 1.8384, -0.5395,  1.2612],
        [ 1.1075, -0.0135,  0.2168],
        [ 0.8887,  2.0578, -1.5809],
        [ 1.0810,  0.8828, -1.6193]])


Addition: providing an output tensor as argument

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 3.3168,  2.4710,  0.1030],
        [ 1.8384, -0.5395,  1.2612],
        [ 1.1075, -0.0135,  0.2168],
        [ 0.8887,  2.0578, -1.5809],
        [ 1.0810,  0.8828, -1.6193]])


Addition: in-place

In [11]:
# adds x to y
y.add(x)
print(y)

tensor([[0.4487, 0.1423, 0.0800],
        [0.9094, 0.4736, 0.0876],
        [0.9392, 0.2206, 0.0149],
        [0.3292, 0.0686, 0.5706],
        [0.9039, 0.5475, 0.3947]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [12]:
a = torch.ones(3, 1)
b = torch.rand(3, 1)
print(a)
print(b)

tensor([[1.],
        [1.],
        [1.]])
tensor([[0.0945],
        [0.3353],
        [0.1921]])


In [13]:
print(a.add(b))
print(a)
print(a.add_(b)) # in-place
print(a)

tensor([[1.0945],
        [1.3353],
        [1.1921]])
tensor([[1.],
        [1.],
        [1.]])
tensor([[1.0945],
        [1.3353],
        [1.1921]])
tensor([[1.0945],
        [1.3353],
        [1.1921]])


You can use standard NumPy-like indexing with all bells and whistles!

In [14]:
print(x[:, 1])

tensor([ 2.3287, -1.0131, -0.2340,  1.9892,  0.3354])


Resizing: If you want to resize/reshape tensor, you can use `torch.view`:

In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.9366])
0.936574399471


**Read later**:
- 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, tec., are describe [here](https://pytorch.org/docs/stable/torch.html).

## NumPy Bridge
Vonverting a Torch Tensor to NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor
See how changing the np array changed the Torch Tensor automatically

In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

### CUDA Tensors
Tensors can be moved onto any device using the `.to` method.

In [22]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda") # a CUDA device object
    y = torch.ones_like(x, device=device) # directly create a tensor on GPU
    x = x.to(device) # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) # ``.to`` can also change dtype together!